<a href="https://colab.research.google.com/github/VemavarapuNagSahithi/git-demo/blob/main/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Basics
a=np.array([1,3,5])
a

array([1, 3, 5])

In [11]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype='int16')
b

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [7]:
#get dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [10]:
#get type
a.dtype

dtype('int64')

In [13]:
b.dtype #we inform that dtype of b should be int16

dtype('int16')

In [14]:
#size
a.itemsize

8

In [16]:
b.itemsize #due to given dtype is int16

2

In [18]:
#get total size
print("total size",a.size)
print("bytes",a.size*a.itemsize)
print("using nbytes",a.nbytes)

total size 3
bytes 24
using nbytes 24


In [19]:
print("total sizeof b ",b.size)
print("bytes of b",b.size*b.itemsize)
print("using nbytes of b",b.nbytes)

total sizeof b  6
bytes of b 12
using nbytes of b 12


Accessing/Changing specific elements,rows,columns etc

In [20]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
#get a specific element [r,c]
print(a[1,5])
print(a[1,-2])

13
13


In [25]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#get a specific column
a[:,2]

array([ 3, 10])

In [27]:
#getting some more fancy using [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [28]:
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [29]:
a[:,2]=5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [31]:
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3d example

In [34]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [38]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing different types of arrays

In [39]:
#all zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#all ones
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [41]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [42]:
#any other number using full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
#similar to above we can use for full
np.full(b.shape,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [44]:
#random decimal number
np.random.rand(4,2)

array([[0.95883576, 0.67950106],
       [0.09915524, 0.89964302],
       [0.87120228, 0.3673238 ],
       [0.56223919, 0.36001445]])

In [45]:
#similarly if we want to use "a" array like this then we use random_sample
np.random.random_sample(a.shape)

array([[0.59172101, 0.50071716, 0.19094967, 0.51632501, 0.34273883,
        0.22874288, 0.75702889],
       [0.18747293, 0.35360026, 0.6277136 , 0.03088655, 0.39514413,
        0.50624667, 0.74861924]])

In [46]:
#random integers
np.random.randint(7,size=(3,3))

array([[5, 2, 5],
       [0, 6, 6],
       [5, 4, 0]])

In [47]:
#idntity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
o=np.ones((5,5))
print("o array")
print(o)
z=np.zeros((3,3))
print("z array")
print(z)
z[1,1]=9
print("z array of mid value 9 ")
print(z)
o[1:4,1:4]=z
print("total output of the matrix")
print(o)

o array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
z array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
z array of mid value 9 
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
total output of the matrix
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


MATHEMATICS

In [57]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [59]:
print("sum",a+2)
print("subtract",a-2)
print("multiply",a*2)
print("divided by 2 ",a/2)
print("power of 2 ",a**2)

sum [3 4 5 6]
subtract [-1  0  1  2]
multiply [2 4 6 8]
divided by 2  [0.5 1.  1.5 2. ]
power of 2  [ 1  4  9 16]


In [60]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [61]:
#take a sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear algebra

In [64]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [66]:
#find the determinant
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

STATISTICS

In [68]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats)

1

In [70]:
np.max(stats)

6

In [72]:
np.sum(stats)

21

In [73]:
np.sum(stats,axis=0)

array([5, 7, 9])

Reorganising array

In [75]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [77]:
#vertically Stacking array
v1=[1,2,3]
v2=[4,5,6]
vert=np.vstack((v1,v2,v1,v2))
print(vert)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [78]:
#horizontal stacking of array
h1=np.zeros((2,3))
h2=np.ones((2,2))
hori=np.hstack((h1,h2))
print(hori)

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]


MISCELLANEOUS

In [88]:
from google.colab import files
uploaded = files.upload()

Saving data.txt to data (1).txt


In [104]:
import numpy as np

# Load the file
data = np.genfromtxt('/content/data.txt',dtype=str)

# Check the data
print(data)
data.astype('str')

['1,2,3,4,5,6,7,8,9,12,13,14,15,16,71,18,29,47'
 '36,56,57,57,64,74,87,27,57,44,47,67,12,34,67']


array(['1,2,3,4,5,6,7,8,9,12,13,14,15,16,71,18,29,47',
       '36,56,57,57,64,74,87,27,57,44,47,67,12,34,67'], dtype='<U44')